package com.pdx.model.chat;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.List;

@Data
public class GPTResponse {

    @ApiModelProperty(value = "The unique identifier of the response")
    private String id;

    @ApiModelProperty(value = "The object type of the response")
    private String object;

    @ApiModelProperty(value = "The creation time of the response")
    private String created;

    @ApiModelProperty(value = "The model used to generate the response")
    private String model;

    @ApiModelProperty(value = "The choices generated by the model")
    private List<GPTChoice> choices;

}
